name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          # os: [macOS-latest, ubuntu-18.04, windows-latest]
          os: [ubuntu-18.04]
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.0.11
      - name: Install Iceoryx Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libacl1-dev libncurses5-dev pkg-config
      - name: Checkout Sources
        uses: actions/checkout@v2
        with:
          path: src/rmw_iceoryx
      - name: Checkout Iceoryx
        uses: actions/checkout@v2
        with:
          repository: eclipse/iceoryx
          path: src/iceoryx
          ref: master
      - run: colcon build
      - run: colcon test
      - run: colcon test-results --verbose
